# Generated by Django 2.1.2 on 2018-10-05 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('vendor', models.CharField(default='null', max_length=20, verbose_name='vendor')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('description', models.TextField(blank=True, null=exchange.models.Trade, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15, verbose_name='location')),
                ('rate_per_coin', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='rate per coin')),
                ('minimum_amount', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='minimum amount')),
                ('maximum_amount', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='maximum_amount')),
                ('terms', models.TextField(verbose_name='terms')),
                ('instructions', models.TextField(verbose_name='instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Coin')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='amount')),
                ('rate_per_coin', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='rate per coin')),
                ('status', models.CharField(max_length=8, verbose_name='trade status')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='buyer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Offer', verbose_name='offer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='seller')),
            ],
        ),
    ]
