# Generated by Django 2.1.2 on 2018-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='vendor',
            field=models.CharField(max_length=20, verbose_name='vendor'),
        ),
    ]
