# Generated by Django 2.1.2 on 2018-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20181005_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='vendor',
            field=models.CharField(max_length=100, verbose_name='vendor'),
        ),
    ]
