# Generated by Django 2.1.2 on 2018-10-05 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20181005_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
