# Generated by Django 2.1.2 on 2018-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20181016_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_id',
            field=models.CharField(max_length=10, null=True, verbose_name='offer id'),
        ),
    ]
