# Generated by Django 2.1.2 on 2018-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_offer_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='payment_channel',
            field=models.CharField(choices=[('P2P', 'Peer to peer'), ('ESS', 'Escrow service')], default='P2P', max_length=50, verbose_name='payment channel'),
        ),
    ]
