# Generated by Django 2.1.2 on 2018-10-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_trade_payment_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(max_length=10, null=True, verbose_name='trade id'),
        ),
    ]
