# Generated by Django 2.1.2 on 2018-10-07 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181006_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='contact.Contact', to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
    ]
